### ISSUE TITLE
[Consumer] Mock up what data to show inside map bubbles

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#5]
Store name?
Hours?
Address?
...?

Look at the api to see what data we have.

**Comment by picketae** [comment]
<img width="432" alt="screen shot 2016-05-09 at 8 12 53 pm" src="https://cloud.githubusercontent.com/assets/19158936/15132766/88355d74-1622-11e6-9e72-f846f1ab2fee.png">

I have been messing around with some preliminary designs for out pop-in bubbles. You'll have to forgive my clunky design, as I am still getting back in to the swing of programming, but this helps provide a visual idea of what we may want here.

After discussing with Anthony, we realized that having hours for each day of the week presents multiple issues. We should instead list this as how much longer the truck is expected to be at a certain location as well as potentially showing future hours. 

Providing an address also could be a little tricky as these are mobile trucks. We're not sure if there will be locations loaded in from each truck or if we should give a general location or how exactly this will look.

I will be working on my CSS skills so that this information can be displayed a bit better.

**Comment by AnthonyAstige** [comment]
Related from today's conversation: For the MVP each bubble on the map is going to be a single event. This concept relies on https://github.com/codeforeauclaire/foodtrucks/issues/17.

**Comment by AnthonyAstige** [comment]
@aaronsalmon Last week you were working on wire frame stuff, iirc for the vendor side primarily but some stuff that may apply here.  Can you throw it up somewhere and link it here for reference?

**Comment by aaronsalmon** [comment]
implement mockup.  

<img src="https://www.dropbox.com/s/l35a62l83169qzr/foodtrucks.png?dl=0">

**Comment by aaronsalmon** [comment]
<img src="http://bit.ly/1WOHTwG">

**Comment by aaronsalmon** [comment]
link goes to trucks list page

truncate description if wicked long.

**Comment by AnthonyAstige** [comment]
Done here, moved remaining to #33
